modLoader="javafml"
loaderVersion="[32,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Epic312/Fruitful/issues/"

[[mods]]
    modId="fruitful"
    version="${file.jarVersion}"
    displayName="Fruitful"
    displayURL="https://discord.gg/BgE4EpP"
    logoFile="logo.png"
    authors="Team Aurora"
    description="Apples, peaches, and oranges grow on trees! Featuring new dishes made from each."

[[dependencies.fruitful]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.10,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fruitful]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.fruitful]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[3.0.6,)"
    ordering="AFTER"
    side="BOTH"